# Generated by Django 4.2.3 on 2023-07-21 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockInfo',
            fields=[
                ('Ticker', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=200)),
                ('Report_Date', models.DateField()),
                ('Fiscal_Date_End', models.DateField()),
                ('Quarterly_Growth', models.FloatField()),
                ('Days_To_Cover', models.FloatField()),
                ('Estimate', models.FloatField()),
                ('Implied_Move', models.FloatField()),
                ('Market_Cap', models.IntegerField()),
                ('Website', models.CharField(max_length=200)),
            ],
        ),
    ]
