# Generated by Django 4.2.3 on 2023-07-21 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockinfo',
            name='Quarterly_Growth',
        ),
    ]
